name: msbuild

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build with msbuild
      run: |
        msbuild -p:Configuration=Release -p:RestorePackagesConfig=true -restore
        echo "abbrev_sha=${GITHUB_SHA:0:8}" >> $GITHUB_ENV

    - name: Upload artifacts to action run
      uses: actions/upload-artifact@v2.2.4
      with:
        path: NMSGM/bin/Release
        name: NMSGM-${{ env.abbrev_sha }}

  release:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    steps:
    - name: Set environment variables
      run: |
        echo "abbrev_sha=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
        echo "tag_name=${GITHUB_REF:10}" >> $GITHUB_ENV

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: NMSGM-${{ env.abbrev_sha }}
        path: NMSGM-${{ env.tag_name }}

    - name: Compress artifacts for release
      run: zip -r NMSGM-${tag_name}.zip NMSGM-${tag_name}/

    - name: Save artifact in release
      uses: softprops/action-gh-release@v1
      with:
        files: NMSGM-${{ env.tag_name }}.zip
