//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMSGM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMSGM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes in recent versions:
        ///
        ///[0.5.1.0]
        ///- [FIX] Savegames could not be restored if the savegame profile folder did not contain a previous save
        ///
        ///[0.5.0.1]
        ///- [NEW] Save restore functionality is now implemented. Including implementation to restore while NMS is running!
        ///- [NEW] When a savegame is restored the savegame that is about to be overwritten is autosaved to the database
        ///- [FIX] Changelog was sometimes not displayed correctly after version upgrades
        ///
        ///[0.4.4.0]
        ///- [FIX] Potential fix/workaround fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangelogInformation {
            get {
                return ResourceManager.GetString("ChangelogInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses Microsoft Application Insights to transmits error and usage statistics (telemety information) in order help the developer understand how the application is used and what errors or crashes occur within the application.
        ///
        ///Examples of the data transmitted are the version of NMSGM you are using, what operating system you are using or debug information in case the application itself crashed.
        ///
        ///Collection of this data is anonymous and does not include any personal information or data.
        ///
        ///I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TelemetryInformation {
            get {
                return ResourceManager.GetString("TelemetryInformation", resourceCulture);
            }
        }
    }
}
